#! /bin/sh
# /etc/init.d/guarddog

### BEGIN INIT INFO
# Provides:          GuardDog
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       Start / stop GuardDog at boot / shutdown. See http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting GuardDog"
    # run application you want to start
    /var/www/GuardDog/GuardDog/build/GuardDog "/var/www/GuardDog/GuardDog" 5 1.7
    ;;
  stop)
    echo "Stopping GuardDog"
    # kill application you want to stop
    killall GuardDog
    ;;
  *)
    echo "Usage: /etc/init.d/guarddog {start|stop}"
    exit 1
    ;;
esac

exit 0
